# Generated by Django 4.2.6 on 2023-11-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinequiz', '0002_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
