# Generated by Django 4.2.6 on 2023-11-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinequiz', '0004_option_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('questionNo', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('submittime', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
