# Generated by Django 4.2.6 on 2023-11-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinequiz', '0005_studentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='score',
        ),
    ]
